CREATE DATABASE BookShop;
USE BookShop;

CREATE TABLE IF NOT EXISTS Books(
	BookNo int(10) NOT NULL AUTO_INCREMENT,
	BookName varchar(255) NOT NULL,
	FirstAuthor varchar(60) NOT NULL,
	SecondAuthor varchar(60) DEFAULT NULL,
	ThirdAuthor varchar(60) DEFAULT NULL,
	FourthAuthor varchar(60) DEFAULT NULL,
	PublisherName varchar(100) NOT NULL,
	Category varchar(100) NOT NULL,
	ISBN varchar(20) NOT NULL,
	Edition varchar(20) NOT NULL,
	Year int(4) NOT NULL,
	Cost int(12) NOT NULL,
	Synopsis varchar(4000) NOT NULL,
	AboutAuthors varchar(4000) NOT NULL,
	TopicsCovered varchar(4000) NOT NULL,
	ContentsCDROM varchar(4000) NOT NULL,
	PRIMARY KEY (BookNo),
	UNIQUE KEY ISBN(ISBN));

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Oracle For Professionals', 'Sharanam Shah', 'Vaishali Shah', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Database', '978-81-8404-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work. It provides all of the basics you would expect to find in an introductory text and at the same time serves those who want to harness the unexploited overlooked power of Oracle SQL and PLSQL with an easy to follow format and numerous real examples based on most commonly used business database models.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect. He currently consults with several software houses in Mumbai India to help them design and manage database applications. Vaishali Shah his wife co-author and a Technical Writer by profession has a rich experience of designing developing and managing database systems.', 'Oracle, SQL, PLSQL, Java, PHP', 'Source Code, Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Practical Java Project For Beginners', 'Anil Kumar', 'Brady Schauf', 'Mihai Bucica', 'Tom Laszewski', 'Wrox', 'Java', '10: 81-8404-342-2', 'Third', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('JavaServer Pages For Beginners', 'Sharanam Shah', 'Vaishali Shah', 'Ivan Bayross', 'Cynthia Bayross', 'Wrox', 'Java', '10: 81-8404-359-7', 'Second', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development using Java Server Pages. Learning web development is done through a set of examples and hands on exercises', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader together with Mrs. Vaishali Shah gentle but dependable application developer work well together.', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages - Getting Started Working With JSP EL Expressions Java Beans Databases', 'Setup Files for Java EE 5SDK MySQL Database MySQL Connector/J JRE Source Code for every example in this book Source Code for solutions to Hands On Exercise');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('PHP 5.1 For Beginners', 'Sharanam Shah', 'Vaishali Shah', NULL, NULL, 'Packt Publishing Ltd', 'Open Source', '81-8404-075-X', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using object oriented PHP 5.1 as the programming environment. IIS and Apache as the web servers of choice. With a clutch of DBMS as the data store underlay for the applications developed. All run on M.S. Windows and Linux. These are todays programming environments of choice.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Environment Source Code For Every Example In This Book Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Oracle For Beginners', 'A. P. Rajshekhar', 'Vaishali Shah', NULL, NULL, 'Packt Publishing Ltd', 'Database', '978-181-8404-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect.', 'Oracle SQL PLSQL Java PHP', 'Source Code Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Oracle And PHP On Linux For Beginners', 'Brady Schauf', 'A. P. Rajshekhar', NULL, NULL, 'Packt Publishing Ltd', 'Application Development', '81-7366-624-9', 'Fourth', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using PHP as a front-end programming tool Apache as the web server and Oracle 10g as a DBMS of choice all run on Linux. Learning web development is done through a set of examples and is finally strongly reinforced by the development of a Personnel Management System. The Personnel Management System is developed using PHP served via Apache Web Server using Oracle 10g as the data store. This is something web based application development companies worldwide require today. A special chapter covering the installation of Red Hat Linux Advanced Server 3 is included.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Framework, Installation, Apache Web Server Installation Of Oracle 10g, SQL Techniques', 'Setup Files For Apache And PHP, Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('JSP Projects For Beginners', 'Anil Kumar Gupta', 'Sharanam Shah', 'Mihai Bucica', 'Tom Laszewski', 'Packt Publishing Ltd', 'Java', '81-2404-342-2', 'Third', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Java Server Pages', 'Vaishali Shah', 'Sharanam Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Packt Publishing Ltd', 'Java', '81-7774-359-7', 'Second', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development using Java Server Pages. Learning web development is done through a set of examples and hands on exercises', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader together with Mrs. Vaishali Shah gentle but dependable application developer work well together.', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages - Getting Started Working With JSP EL Expressions Java Beans Databases', 'Setup Files for Java EE 5SDK MySQL Database MySQL Connector/J JRE Source Code for every example in this book Source Code for solutions to Hands On Exercise');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('PHP For Professionals', 'Vaishali Shah', 'A. P. Rajshekhar', NULL, NULL, 'Packt Publishing Ltd', 'Application Development', '81-8404-073-D', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using object oriented PHP 5.1 as the programming environment. IIS and Apache as the web servers of choice. With a clutch of DBMS as the data store underlay for the applications developed. All run on M.S. Windows and Linux. These are todays programming environments of choice.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Environment Source Code For Every Example In This Book Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MySQL For Beginners', 'Sharanam Shah', 'Vaishali Shah', NULL, NULL, 'Wrox', 'Database', '978-481-8404-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect.', 'Oracle SQL PLSQL Java PHP', 'Source Code Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Oracle On Linux', 'Vaishali Shah', 'A. P. Rajshekhar', NULL, NULL, 'Wrox', 'Database', '81-736-684-9', 'First', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using PHP as a front-end programming tool Apache as the web server and Oracle 10g as a DBMS of choice all run on Linux. Learning web development is done through a set of examples and is finally strongly reinforced by the development of a Personnel Management System. The Personnel Management System is developed using PHP served via Apache Web Server using Oracle 10g as the data store. This is something web based application development companies worldwide require today. A special chapter covering the installation of Red Hat Linux Advanced Server 3 is included.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Framework, Installation, Apache Web Server Installation Of Oracle 10g, SQL Techniques', 'Setup Files For Apache And PHP, Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Java 1.5', 3, 'Vaishali Shah', 11, 12, 'Wrox', 'Java', '81-8334-342-2', 'First', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum. Besides them this book can be of great use for professionals involved in software development or technical services. This book is for anyone who wants to program dynamic feature rich web applications in JSP.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer. He did B.E. from University of Pune and also C level from DOEACC Society Govt. of India.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5 Running JSP Project');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('JSTL For Beginners', 5, 'Sharanam Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Java', '81-8654-359-7', 'Third', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development using Java Server Pages.', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader.', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages - Getting Started Working With JSP EL Expressions Java Beans Databases', 'Setup Files for Java EE 5SDK MySQL Database Source Code for every example in this book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('PHP For Professionals', 'Vaishali Shah', 'A. P. Rajshekhar', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Application Development', '81-8404-035-H', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using object oriented PHP 5.1 as the programming environment. IIS and Apache as the web servers of choice. With a clutch of DBMS as the data store underlay for the applications developed. All run on M.S. Windows and Linux. These are todays programming environments of choice.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Environment Source Code For Every Example In This Book Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Oracle Projects', 'Sharanam Shah', 'David Byrd', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Application Development', '978-681-8404-526', 'First', 2008, 750, '<p>Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work. It provides all of the basics you would expect to find in an introductory text and at the same time serves those who want to harness the unexploited overlooked power of Oracle SQL and PLSQL with an easy to follow format and numerous real examples based on most commonly used business database models.</p>', '<p>The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect. He currently consults with several software houses in Mumbai India to help them design and manage database applications. Vaishali Shah his wife co-author and a Technical Writer by profession has a rich experience of designing developing and managing database systems.</p>', '<p>Oracle, SQL, PLSQL, Java, PHP</p>', '<p>Source Code, Oracle XE 10g</p>');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Linux', 'Vaishali Shah', 'Sharanam Shah', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Open Source', '81-366-684-9', 'First', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together.', 'Framework Installation Apache Web Server Installation Of Oracle 10g SQL Techniques', 'Setup Files For Apache And PHP Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Oracle 10g', 'Vaishali Shah', 'David Byrd', 'Mihai Bucica', 'Tom Laszewski', 'Shroff Publishers and Distributors Private Limited', 'Database', '81-8404-342-33', 'First', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Struts For Beginners', 'Carly Taylor', 'Brady Schauf', 'A. P. Rajshekhar', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Application Development', '81-8404-999-7', 'First', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development using Java Server Pages.', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages', 'Setup Files for Java EE 5SDK MySQL DatabaseSource Code for every example');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('PHP And MySQL', 'Carly Taylor', 'Deepika Vohra', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Application Development', '81-8404-0215-Q', 'Second', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using object oriented PHP 5.1 as the programming environment. IIS and Apache as the web servers of choice. With a clutch of DBMS as the data store underlay for the applications developed. All run on M.S. Windows and Linux. These are todays programming environments of choice.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Environment Source Code For Every Example In This Book Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Oracle 11g', 'Sharanam Shah', 'Vaishali Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Apress Inc', 'Database', '978-851-8404-526', 'Fourth', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work. It provides all of the basics you would expect to find in an introductory text and at the same time serves those who want to harness the unexploited overlooked power of Oracle SQL and PLSQL with an easy to follow format and numerous real examples based on most commonly used business database models.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect. He currently consults with several software houses in Mumbai India to help them design and manage database applications. Vaishali Shah his wife co-author and a Technical Writer by profession has a rich experience of designing developing and managing database systems.', 'Oracle, SQL, PLSQL, Java, PHP', 'Source Code, Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MySQL 6', 'Anil Kumar Gupta', 'Sharanam Shah', 'Vaishali Shah', 'A. P. Rajshekhar', 'Apress Inc', 'Database', '81-8404-342-44', 'First', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Hibernate For Beginners', 'Carly Taylor', 'Brady Schauf', 'Anil Kumar Gupta', 'Vaishali Shah', 'Apress Inc', 'Application Development', '81-8432-329-7', 'First', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages', 'Setup Files for Java EE 5SDK MySQL Database Source Code for solutions to Hands On Exercise');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MySQL Projects', 'Brady Schauf', 'Vaishali Shah', 'Sharanam Shah', 'A. P. Rajshekhar', 'BpB', 'Database', '81-8404-075-R', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Application Development Using JSP', 'Aaron Winborn', 'Vaishali Shah', 'Sharanam Shah', 'Anil Kumar Gupta', 'BpB', 'Project Management', '978-81-84404-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect.', 'Oracle SQL PLSQL Java PHP', 'Source Code Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Windows Server 2003', 'David Byrd', 'Sharanam Shah', 'Vaishali Shah', 'A. P. Rajshekhar', 'BpB', 'Microsoft', '81-7366-684-X', 'First', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader', 'Framework Installation Apache Web Server Installation Of Oracle 10g SQL Techniques', 'Setup Files For Apache And PHP Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Windows XP', 'Deepika Vohra', 'Sharanam Shah', 'Vaishali Shah', 'A. P. Rajshekhar', 'BpB', 'Networking', '81-3303-342-2', 'First', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Fedora Core 8', 'Sharanam Shah', 'Vaishali Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'BpB', 'Open Source', '81-2224-359-7', 'First', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development using Java Server Pages. Learning web development is done through a set of examples and hands on exercises', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader together with Mrs. Vaishali Shah gentle but dependable application developer work well together.', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages - Getting Started Working With JSP EL Expressions Java Beans Databases', 'Setup Files for Java EE 5SDK MySQL Database MySQL Connector/J JRE Source Code for every example in this book Source Code for solutions to Hands On Exercise');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Suse Linux', 'Sharanam Shah', 'Anil Kumar Gupta', 'Brady Schauf', 'Tom Laszewski', 'BpB', 'Open Source', '81-8404-075-W', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using object oriented PHP 5.1 as the programming environment. IIS and Apache as the web servers of choice. With a clutch of DBMS as the data store underlay for the applications developed. All run on M.S. Windows and Linux. These are todays programming environments of choice.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Environment Source Code For Every Example In This Book Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MS Windows 98', 'A. P. Rajshekhar', 'Vaishali Shah', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Operating System', '33-181-8404-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect.', 'Oracle SQL PLSQL Java PHP', 'Source Code Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MS Windows Vista', 'Brady Schauf', 'A. P. Rajshekhar', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Operating System', '44-7366-624-9', 'First', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together.', 'Framework Installation Apache Web Server Installation Of Oracle 10g SQL Techniques', 'Setup Files For Apache And PHP Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MS Windows XP', 'Anil Kumar Gupta', 'Sharanam Shah', 'Mihai Bucica', 'Tom Laszewski', 'Shroff Publishers and Distributors Private Limited', 'Operating System', '99-2404-342-2', 'First', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Windows Tricks', 'Vaishali Shah', 'Sharanam Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Operating System', '81-6664-359-7', 'First', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages', 'Setup Files for Java EE 5SDK MySQL Database Source Code for solutions to Hands On Exercise');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Registry Tweaks For Windows', 'Vaishali Shah', 'A. P. Rajshekhar', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Operating System', '54-8874-073-D', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using object oriented PHP 5.1 as the programming environment. IIS and Apache as the web servers of choice. With a clutch of DBMS as the data store underlay for the applications developed. All run on M.S. Windows and Linux. These are todays programming environments of choice.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Environment Source Code For Every Example In This Book Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Open Office Excel', 'Sharanam Shah', 'Vaishali Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Spreadsheets', '333-481-8404-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work. It provides all of the basics you would expect to find in an introductory text and at the same time serves those who want to harness the unexploited overlooked power of Oracle SQL and PLSQL with an easy to follow format and numerous real examples based on most commonly used business database models.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect. He currently consults with several software houses in Mumbai India to help them design and manage database applications. Vaishali Shah his wife co-author and a Technical Writer by profession has a rich experience of designing developing and managing database systems.', 'Oracle, SQL, PLSQL, Java, PHP', 'Source Code, Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MS Excel', 'Vaishali Shah', 'A. P. Rajshekhar', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Spreadsheets', '232-736-684-9', 'First', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using PHP as a front-end programming tool Apache as the web server and Oracle 10g as a DBMS of choice all run on Linux. Learning web development is done through a set of examples and is finally strongly reinforced by the development of a Personnel Management System. The Personnel Management System is developed using PHP served via Apache Web Server using Oracle 10g as the data store. This is something web based application development companies worldwide require today. A special chapter covering the installation of Red Hat Linux Advanced Server 3 is included.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Framework, Installation, Apache Web Server Installation Of Oracle 10g, SQL Techniques', 'Setup Files For Apache And PHP, Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Tricks In MS Excel', 'A. P. Rajshekhar', 'Sharanam Shah', 'Mihai Bucica', 'Tom Laszewski', 'Shroff Publishers and Distributors Private Limited', 'Spreadsheets', '767-8334-342-2', 'First', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum. Besides them this book can be of great use for professionals involved in software development or technical services. This book is for anyone who wants to program dynamic feature rich web applications in JSP.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer. He did B.E. from University of Pune and also C level from DOEACC Society Govt. of India.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5 Running JSP Project');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MS Word Tips and Tricks', 'Vaishali Shah', 'Sharanam Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Word Processors & Editors', '81-4444-359-7', 'First', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development using Java Server Pages. Learning web development is done through a set of examples and hands on exercises', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader together with Mrs. Vaishali Shah gentle but dependable application developer work well together.', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages - Getting Started Working With JSP EL Expressions Java Beans Databases', 'Setup Files for Java EE 5SDK MySQL Database MySQL Connector/J JRE Source Code for every example in this book Source Code for solutions to Hands On Exercise');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Star Office', 'Vaishali Shah', 'A. P. Rajshekhar', 'Sharanam Shah', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Word Processors & Editors', '81-9898-035-H', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using object oriented PHP 5.1 as the programming environment. IIS and Apache as the web servers of choice. With a clutch of DBMS as the data store underlay for the applications developed. All run on M.S. Windows and Linux. These are todays programming environments of choice.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Environment Source Code For Every Example In This Book Solutions To Hands On Exercises');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Joomla', 'Sharanam Shah', 'Vaishali Shah', NULL, NULL, 'Apress Inc', 'Content Management', '888-181-8404-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work. It provides all of the basics you would expect to find in an introductory text and at the same time serves those who want to harness the unexploited overlooked power of Oracle SQL and PLSQL with an easy to follow format and numerous real examples based on most commonly used business database models.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect. He currently consults with several software houses in Mumbai India to help them design and manage database applications. Vaishali Shah his wife co-author and a Technical Writer by profession has a rich experience of designing developing and managing database systems.', 'Oracle, SQL, PLSQL, Java, PHP', 'Source Code, Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Mambo', 'Vaishali Shah', 'A. P. Rajshekhar', 'Sharanam Shah', 'Carly Taylor', 'Apress Inc', 'Content Management', '99-7996-624-9', 'First', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development using PHP as a front-end programming tool Apache as the web server and Oracle 10g as a DBMS of choice all run on Linux. Learning web development is done through a set of examples and is finally strongly reinforced by the development of a Personnel Management System. The Personnel Management System is developed using PHP served via Apache Web Server using Oracle 10g as the data store. This is something web based application development companies worldwide require today. A special chapter covering the installation of Red Hat Linux Advanced Server 3 is included.', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together. One proving a perfect foil for the other. The pair of them make quite a formidable team in multi-tier client / server application development. In this book they share their many man-years of development experience using a simple to follow hands on kind of approach.', 'Framework, Installation, Apache Web Server Installation Of Oracle 10g, SQL Techniques', 'Setup Files For Apache And PHP, Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('TCPIP', 'Anil Kumar Gupta', 'Sharanam Shah', 'Mihai Bucica', 'Tom Laszewski', 'Apress Inc', 'Internet', '99-5544-342-2', 'First', 2007, 150, 'This book can be useful for students pursuing B.E. M.C.A M.Sc. IGNOU BCA B.Sc. courses who have to make and submit a project as part of their curriculum.', 'B. M. Harwani is teaching since 13 years at his Computer Institute - Microchip Computer Education (MCE) Ajmer.', 'All commands included in the project with yntax are explained. The working of programs is explained in easy English.', 'Tomcat 5.5 a popular servlet and JSP engine J2SE SDK version 1.5');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Hacking', 'Vaishali Shah', 'Sharanam Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Internet', '81-6664-6556-7', 'First', 2007, 500, 'The book has been written to provide genuine knowledge to programmers who wish to learn Java Server side Web based application development', 'The authors Mr. Ivan Bayross an M. Tech from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader', 'Java Servlets And Java Server Pages - Introduction Basics Of Java Server Pages', 'Setup Files for Java EE 5SDK MySQL Database Source Code for solutions to Hands On Exercise');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('IE Tweaks', 'Vaishali Shah', 'A. P. Rajshekhar', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Web Design', '44-8334-073-D', 'First', 2006, 650, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together.', 'Setting Up The Framework - Intallations The Fundamentals Of PHP - Basics', 'Setup Files To Build The Runtime Programming Source Code For Every Example In This Book');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('Dreamweaver', 'Sharanam Shah', 'Vaishali Shah', 'A. P. Rajshekhar', 'Aaron Winborn', 'Shroff Publishers and Distributors Private Limited', 'Web Design', '333-666-7774-526', 'First', 2008, 750, 'Designed for new and experienced developers this book is an essential guide for putting Oracle SQL and PL/SQL to work.', 'The author Sharanam Shah has 7+ years of IT experience as a Developer Database Designer Technical Writer Systems Analyst and a Lead Architect.', 'Oracle SQL PLSQL Java PHP', 'Source Code Oracle XE 10g');

INSERT INTO Books (BookName, FirstAuthor, SecondAuthor, ThirdAuthor, FourthAuthor, PublisherName, Category, ISBN, Edition, Year, Cost, Synopsis, AboutAuthors, TopicsCovered, ContentsCDROM) VALUES
('MS Frontpage', 'Vaishali Shah', 'A. P. Rajshekhar', NULL, NULL, 'Shroff Publishers and Distributors Private Limited', 'Web Design', '111-736-684-9', 'First', 2005, 500, 'The book has been written to provide genuine domain knowledge to programmers who wish to learn web based application development', 'The authors Ivan Bayross an M. Tech in DBMS from Manchester University UK and Mr. Sharanam Shah a Post Graduate from C-DAC and Sr. Project Leader work very well together.', 'Framework Installation Apache Web Server Installation Of Oracle 10g SQL Techniques', 'Setup Files For Apache And PHP Source Code For Every Example In This Book');


CREATE TABLE IF NOT EXISTS SystemUsers(
	UserNo int(10) NOT NULL AUTO_INCREMENT,
	Username varchar(30) NOT NULL,
	Password varchar(30) NOT NULL,
	PRIMARY KEY (UserNo),
	UNIQUE KEY Username(Username));

INSERT INTO SystemUsers(Username, Password)VALUES('admin', 'admin');
